import { Inter } from "next/font/google";

import "tailwindcss/tailwind.css";
import Providers from "./api/providers/Providers";
import "./globals.scss";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <Providers>
      <html lang="en">
        <Head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
        </Head>
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>
  );
}
